doc_cnpdocument:
    resource: "@DocBundle/Resources/config/routing/parametrage.yml"
    prefix:   /parametrage

doc_reseau:
    resource: "@DocBundle/Resources/config/routing/reseau.yml"
    prefix:   /reseau

doc_version:
    resource: "@DocBundle/Resources/config/routing/version.yml"
    prefix:   /version

doc_homepage:
    path:     /home
    defaults: { _controller: DocBundle:Default:index }
