doc_cnpdocument:
    resource: "@DocBundle/Resources/config/routing/parametrage.yml"
    prefix:   /parametrage

doc_reseau:
    resource: "@DocBundle/Resources/config/routing/reseau.yml"
    prefix:   /reseau

doc_homepage:
    path:     /
    defaults: { _controller: DocBundle:Default:index }
