<?php

namespace DocBundle\Repository;

use DocBundle\Entity\Version;


/**
 * ArchiveParamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchiveParamRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Version $version
     * @return array
     */
    public function getArchivesByVersion(Version $version)
    {
        $qb = $this->createQueryBuilder('ar');
        $qb->join('ar.version', 'v')
            ->addSelect('v')
            ->where('v.id = :id')
            ->setParameter('id', $version->getId());
        return $qb
            ->getQuery()
            ->getResult();
    }
}
