<?php

namespace DocBundle\Repository;

/**
 * ArchiveParamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchiveParamRepository extends \Doctrine\ORM\EntityRepository
{
}
