<?php

namespace DocBundle\Repository;

/**
 * ArchivePdfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchivePdfRepository extends \Doctrine\ORM\EntityRepository
{
}
