<?php

namespace DocBundle\Repository;

/**
 * CnpDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CnpDocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
