<?php

namespace DocBundle\Repository;

/**
 * CnpDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametrageRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $reseauId
     * @return array
     */
    public function getParametrageByReseau($reseauId)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->join('p.reseau', 'res')
            ->join('p.pdfSource', 'pdf')
            ->addSelect('res')
            ->addSelect('pdf')
            ->where('res.id = :id')
            ->setParameter('id', $reseauId)
            ->orderBy('p.ordre', 'ASC');
        return $qb
            ->getQuery()
            ->getResult();
    }

    /**
     * @return array
     */
    public function getParametrages()
    {
        $qb = $this->createQueryBuilder('p');
        $qb->join('p.reseau', 'res')
            ->join('p.pdfSource', 'pdf')
            ->addSelect('res')
            ->addSelect('pdf')
            ->orderBy('p.ordre', 'ASC');
        return $qb
            ->getQuery()
            ->getResult();
    }

    /**
     * @return array
     */
    public function findOneWithPdf($id)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->join('p.pdfSource', 'pdf')
            ->addSelect('pdf')
            ->where('p.id = :id')
            ->setParameter('id', $id);
        return $qb
            ->getQuery()
            ->getResult();
    }
}
