<?php

namespace DocBundle\Repository;

/**
 * PdfDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PdfDocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
