<?php

namespace DocBundle\Repository;

/**
 * PdfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PdfRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findPdf($id)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->select('p')
            ->from('DocBundle:Pdf', 'p')
            ->join('DocBundle:Parametrage', 'param')
            ->where('param.id = :id')
            ->setParameter('id', $id);

        return $qb
            ->getQuery()
            ->getResult();
    }
}
