<?php

namespace DocBundle\Repository;

/**
 * ReseauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReseauRepository extends \Doctrine\ORM\EntityRepository
{
}
