<?php

namespace DocBundle\Repository;

use DocBundle\Entity\Reseau;
use DocBundle\Entity\Version;

/**
 * VersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function getClosedByReseau(Reseau $reseau)
    {
        $qb = $this->createQueryBuilder('v');
        $qb->join('v.reseau', 'res')
            ->addSelect('res')
            ->where('v.enCours = 0')
            ->andWhere('res.id = :id')
            ->setParameter('id', $reseau->getId());
        return $qb
            ->getQuery()
            ->getResult();
    }
}
