# redirecting the admin home
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: fos_user_security_login
        permanent: true
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

doc:
    resource: "@DocBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
