cnpdocument_index:
    path:     /
    defaults: { _controller: "DocBundle:CnpDocument:index" }
    methods:  GET

cnpdocument_show:
    path:     /{id}/show
    defaults: { _controller: "DocBundle:CnpDocument:show" }
    methods:  GET

cnpdocument_show_pdf:
    path:     /{id}/pdf
    defaults: { _controller: "DocBundle:CnpDocument:showPdf" }
    methods:  GET

cnpdocument_new:
    path:     /new
    defaults: { _controller: "DocBundle:CnpDocument:new" }
    methods:  [GET, POST]

cnpdocument_edit:
    path:     /{id}/edit
    defaults: { _controller: "DocBundle:CnpDocument:edit" }
    methods:  [GET, POST]

cnpdocument_delete:
    path:     /{id}/delete
    defaults: { _controller: "DocBundle:CnpDocument:delete" }
    methods:  DELETE
