parametrage_index:
    path:     /{page}
    defaults: { _controller: "DocBundle:Parametrage:index", page: 1 }
    methods:  GET

parametrage_show:
    path:     /{id}/show
    defaults: { _controller: "DocBundle:Parametrage:show" }
    methods:  GET

parametrage_show_pdf:
    path:     /{id}/pdf
    defaults: { _controller: "DocBundle:Parametrage:showPdf" }
    methods:  GET

parametrage_show_archive_pdf:
    path:     /{id}/archivepdf
    defaults: { _controller: "DocBundle:Parametrage:showArchivePdf" }
    methods:  GET

parametrage_new:
    path:     /new
    defaults: { _controller: "DocBundle:Parametrage:new" }
    methods:  [GET, POST]

parametrage_edit:
    path:     /{id}/edit
    defaults: { _controller: "DocBundle:Parametrage:edit" }
    methods:  [GET, POST]

parametrage_delete:
    path:     /{id}/delete
    defaults: { _controller: "DocBundle:Parametrage:delete" }
    methods:  [GET, DELETE]

parametrage_cancel_delete:
    path:     /{id}/cancel
    defaults: { _controller: "DocBundle:Parametrage:cancelDelete" }
    methods:  [GET, DELETE]

parametrage_import_csv:
    path:     /csv/import
    defaults: { _controller: "DocBundle:Parametrage:importCSV" }
    methods:  [GET, POST]
