reseau_index:
    path:     /admin
    defaults: { _controller: "DocBundle:Reseau:index" }
    methods:  GET

reseau_show:
    path:     /admin/{id}/show
    defaults: { _controller: "DocBundle:Reseau:show" }
    methods:  GET

reseau_new:
    path:     /admin/new
    defaults: { _controller: "DocBundle:Reseau:new" }
    methods:  [GET, POST]

reseau_edit:
    path:     /admin/{id}/edit
    defaults: { _controller: "DocBundle:Reseau:edit" }
    methods:  [GET, POST]

reseau_delete:
    path:     /admin/{id}/delete
    defaults: { _controller: "DocBundle:Reseau:delete" }
    methods:  [DELETE, GET]

reseau_show_parametrage:
    path:     /{id}/parametrages
    defaults: { _controller: "DocBundle:Reseau:showParametrage" }
    methods:  GET

reseau_generate_params:
    path:     /{id}/generate
    defaults: { _controller: "DocBundle:Reseau:generateParams" }
    methods:  POST

reseau_export_params:
    path:     /{id}/export
    defaults: { _controller: "DocBundle:Reseau:exportParams" }
    methods:  POST