reseau_generate_archive_params:
    path:     /{id}/generate
    defaults: { _controller: "DocBundle:Version:generateParams" }
    methods:  POST

reseau_history_versions:
    path:     /{id}/history
    defaults: { _controller: "DocBundle:Version:paramsHistory" }
    methods:  GET

version_history_params:
    path:     /{id}/version
    defaults: { _controller: "DocBundle:Version:versionHistory" }
    methods:  GET

version_export_params:
    path:     /{id}/export
    defaults: { _controller: "DocBundle:Version:exportHarchiveParams" }
    methods:  POST

parametrage_show_archive_pdf:
    path:     /{id}/archivepdf
    defaults: { _controller: "DocBundle:Version:showArchivePdf" }
    methods:  GET